package com.nextbigtool.backend.entity.tool;

public enum UseCase {
    CONTENT_GENERATION,
    CODE_ASSISTANCE,
    IMAGE_CREATION,
    VIDEO_EDITING,
    DATA_ANALYSIS,
    CUSTOMER_SUPPORT,
    TASK_AUTOMATION,
    EMAIL_WRITING,
    DOCUMENT_SUMMARIZATION,
    TRANSLATION,
    SEO_OPTIMIZATION,
    SOCIAL_MEDIA_MANAGEMENT,
    LEAD_GENERATION,
    COMPETITOR_RESEARCH,
    MEETING_NOTES,
    PRESENTATION_CREATION,
    RESUME_BUILDING,
    LEGAL_DRAFTING,
    FINANCIAL_FORECASTING,
    LEARNING_AND_EDUCATION
}