spring:
  application:
    name: NextBigTool

  datasource:
    url: jdbc:postgresql://localhost:5432/nextbigtool
    password: 8431465059
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    username: cobrother.com@gmail.com
    password: qwex rbyd mamd kgql
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable:
              true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: demo
            client-secret: demo
            scope:
              - openid
              - profile
              - email
            redirect-uri: http://localhost:8080/login/oauth2/code/google

server:
  port: 8080

jwt:
  secret: demo
  expiration: 36000000
  refresh:
    expiration: 2592000000

app:
  frontend-url: http://localhost:3000
  oauth2:
    redirect-uri: http://localhost:3000/auth/callback


cloud:
  aws:
    credentials:
      access-key: demo
      secret-key: demo
      region: ap-south-1
    venture:
      images-bucket: cobrother-storage

razorpay:
  key-id: demo
  key-secret: demo
